In [1]:
import sys
sys.version

'3.13.9 | packaged by Anaconda, Inc. | (main, Oct 21 2025, 19:09:58) [MSC v.1929 64 bit (AMD64)]'

In [1]:
import numpy as np

In [3]:
np.__version__

'2.3.5'

In [4]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [5]:
type(my_list)

list

In [6]:
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [7]:
type(arr)

numpy.ndarray

In [8]:
np.arange()

TypeError: arange() requires stop to be specified.

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(10,0) # Start > stop with positive step, so no values are generated

array([], dtype=int64)

In [15]:
np.arange(-10,5)

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4])

In [16]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [19]:
np.zeros(3)

array([0., 0., 0.])

In [20]:
np.zeros(3,dtype = int)

array([0, 0, 0])

In [22]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
np.ones(2)

array([1., 1.])

In [25]:
np.ones((3,7),dtype = int)

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]])

In [26]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [27]:
np.ones((1,2))

array([[1., 1.]])

In [28]:
np.zeros((5,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [29]:
np.ones((4,2),dtype = int)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [30]:
np.ones((7,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [31]:
np.ones((3,1))

array([[1.],
       [1.],
       [1.]])

In [32]:
np.ones((1,3))

array([[1., 1., 1.]])

In [33]:
np.ones((8,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [2]:
rand()

NameError: name 'rand' is not defined

In [3]:
rand(10)

NameError: name 'rand' is not defined

In [4]:
random.rand(10)

NameError: name 'random' is not defined

In [5]:
np.random.rand(10)

array([4.85219030e-04, 2.40209835e-03, 5.23032646e-01, 4.16922739e-02,
       2.01661636e-02, 8.38050390e-01, 8.53523187e-01, 5.35260519e-01,
       7.65033912e-01, 8.31984097e-01])

In [10]:
np.random.randn(2)

array([ 0.35945264, -0.13687479])

In [11]:
np.random.rand(2)

array([0.43517632, 0.14725538])

In [12]:
np.random.rand(2,4)

array([[0.74544767, 0.57807116, 0.62159571, 0.26759611],
       [0.00986274, 0.28207317, 0.38744873, 0.75200481]])

In [15]:
np.random.randn(3,5,)

array([[ 0.57638896,  0.22410808, -0.87595654,  0.82365413,  1.25717924],
       [ 1.53992333,  0.3855861 , -0.73307058, -0.93203658,  0.37480199],
       [ 0.13126965,  0.2371899 ,  0.05284836,  0.34557558,  0.7223509 ]])

In [22]:
np.random.randint(4)

2

In [26]:
np.random.randint(10,50,(5,5))

array([[41, 13, 14, 26, 40],
       [29, 39, 10, 29, 46],
       [20, 33, 28, 27, 41],
       [23, 29, 32, 43, 30],
       [35, 35, 49, 44, 32]], dtype=int32)

In [34]:
np.random.randint(2,3,(1,1))

array([[2]], dtype=int32)

In [37]:
np.random.randint(0,100,(10,10))

array([[26, 96, 43, 55, 55, 78, 63, 43, 84, 76],
       [ 5,  3, 18,  2, 53,  0, 83, 81, 68, 41],
       [98, 46, 83, 56, 53, 75,  5, 95, 14, 31],
       [66, 18, 69, 31, 73,  1, 60, 33, 13, 54],
       [66,  7, 66,  6, 70, 82, 38, 85, 45,  0],
       [14, 40, 84, 84, 71, 73, 74, 48, 69, 25],
       [96, 81, 42, 48, 77, 61, 48, 52, 91, 68],
       [65, 68, 18, 65,  4,  0, 60, 90, 66, 88],
       [10, 12, 75, 99,  9, 44, 40, 93, 15, 38],
       [75, 15, 38, 86, 68, 69,  6, 21, 66, 35]], dtype=int32)

In [41]:
m = np.random.randint(0,100,(10,10))

In [42]:
m

array([[89, 76, 31, 60, 92,  7, 65,  5,  5, 96],
       [96, 87,  6, 30, 46, 88, 47,  6, 92, 19],
       [47, 13, 78, 11, 25, 72, 44, 11, 30, 88],
       [41, 11, 36, 78, 56, 48, 40, 57, 95, 35],
       [ 4, 43, 94, 27, 95, 61,  1, 24, 78, 52],
       [29, 32, 49, 73, 40, 79,  0, 48, 59, 38],
       [90, 76, 60, 46, 59, 18,  9, 18, 72, 88],
       [83, 42, 27, 92, 58, 78, 87, 37, 91, 60],
       [16, 90, 28,  4, 60, 38, 31, 63, 66, 64],
       [93, 78, 92, 48, 89,  8, 13, 66, 65,  3]], dtype=int32)

# Slicing and indexing

In [43]:
m[2:6]

array([[47, 13, 78, 11, 25, 72, 44, 11, 30, 88],
       [41, 11, 36, 78, 56, 48, 40, 57, 95, 35],
       [ 4, 43, 94, 27, 95, 61,  1, 24, 78, 52],
       [29, 32, 49, 73, 40, 79,  0, 48, 59, 38]], dtype=int32)

In [45]:
m[:2]

array([[89, 76, 31, 60, 92,  7, 65,  5,  5, 96],
       [96, 87,  6, 30, 46, 88, 47,  6, 92, 19]], dtype=int32)

In [47]:
m[2:]

array([[47, 13, 78, 11, 25, 72, 44, 11, 30, 88],
       [41, 11, 36, 78, 56, 48, 40, 57, 95, 35],
       [ 4, 43, 94, 27, 95, 61,  1, 24, 78, 52],
       [29, 32, 49, 73, 40, 79,  0, 48, 59, 38],
       [90, 76, 60, 46, 59, 18,  9, 18, 72, 88],
       [83, 42, 27, 92, 58, 78, 87, 37, 91, 60],
       [16, 90, 28,  4, 60, 38, 31, 63, 66, 64],
       [93, 78, 92, 48, 89,  8, 13, 66, 65,  3]], dtype=int32)

In [48]:
m[-2:-1]

array([[16, 90, 28,  4, 60, 38, 31, 63, 66, 64]], dtype=int32)

In [50]:
m[-2:-3]

array([], shape=(0, 10), dtype=int32)

In [51]:
m[-3:-2]

array([[83, 42, 27, 92, 58, 78, 87, 37, 91, 60]], dtype=int32)

In [52]:
m[-3:-1]

array([[83, 42, 27, 92, 58, 78, 87, 37, 91, 60],
       [16, 90, 28,  4, 60, 38, 31, 63, 66, 64]], dtype=int32)

In [53]:
m

array([[89, 76, 31, 60, 92,  7, 65,  5,  5, 96],
       [96, 87,  6, 30, 46, 88, 47,  6, 92, 19],
       [47, 13, 78, 11, 25, 72, 44, 11, 30, 88],
       [41, 11, 36, 78, 56, 48, 40, 57, 95, 35],
       [ 4, 43, 94, 27, 95, 61,  1, 24, 78, 52],
       [29, 32, 49, 73, 40, 79,  0, 48, 59, 38],
       [90, 76, 60, 46, 59, 18,  9, 18, 72, 88],
       [83, 42, 27, 92, 58, 78, 87, 37, 91, 60],
       [16, 90, 28,  4, 60, 38, 31, 63, 66, 64],
       [93, 78, 92, 48, 89,  8, 13, 66, 65,  3]], dtype=int32)

In [54]:
m[-3:]

array([[83, 42, 27, 92, 58, 78, 87, 37, 91, 60],
       [16, 90, 28,  4, 60, 38, 31, 63, 66, 64],
       [93, 78, 92, 48, 89,  8, 13, 66, 65,  3]], dtype=int32)

In [55]:
m[-1:]

array([[93, 78, 92, 48, 89,  8, 13, 66, 65,  3]], dtype=int32)

In [56]:
m[:-4]

array([[89, 76, 31, 60, 92,  7, 65,  5,  5, 96],
       [96, 87,  6, 30, 46, 88, 47,  6, 92, 19],
       [47, 13, 78, 11, 25, 72, 44, 11, 30, 88],
       [41, 11, 36, 78, 56, 48, 40, 57, 95, 35],
       [ 4, 43, 94, 27, 95, 61,  1, 24, 78, 52],
       [29, 32, 49, 73, 40, 79,  0, 48, 59, 38]], dtype=int32)

In [57]:
m[-4:]

array([[90, 76, 60, 46, 59, 18,  9, 18, 72, 88],
       [83, 42, 27, 92, 58, 78, 87, 37, 91, 60],
       [16, 90, 28,  4, 60, 38, 31, 63, 66, 64],
       [93, 78, 92, 48, 89,  8, 13, 66, 65,  3]], dtype=int32)

In [58]:
m

array([[89, 76, 31, 60, 92,  7, 65,  5,  5, 96],
       [96, 87,  6, 30, 46, 88, 47,  6, 92, 19],
       [47, 13, 78, 11, 25, 72, 44, 11, 30, 88],
       [41, 11, 36, 78, 56, 48, 40, 57, 95, 35],
       [ 4, 43, 94, 27, 95, 61,  1, 24, 78, 52],
       [29, 32, 49, 73, 40, 79,  0, 48, 59, 38],
       [90, 76, 60, 46, 59, 18,  9, 18, 72, 88],
       [83, 42, 27, 92, 58, 78, 87, 37, 91, 60],
       [16, 90, 28,  4, 60, 38, 31, 63, 66, 64],
       [93, 78, 92, 48, 89,  8, 13, 66, 65,  3]], dtype=int32)

In [60]:
row = 3
col = 4

In [61]:
m[row,col]

np.int32(56)

# Reshape

In [62]:
arr1 = np.array([0,1,2,3,4,5,6,7,8,9,10])

In [63]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
arr1.reshape(11,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [65]:
arr1.reshape(1,11)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [66]:
arr1.reshape(1,3)

ValueError: cannot reshape array of size 11 into shape (1,3)

In [67]:
arr2 = np.array([1,2,3,4,5,6,7,8,9,10])

In [68]:
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [69]:
arr2.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [70]:
arr2.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [71]:
arr2.reshape(10,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [72]:
arr2.reshape(1,10)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [73]:
m[:]

array([[89, 76, 31, 60, 92,  7, 65,  5,  5, 96],
       [96, 87,  6, 30, 46, 88, 47,  6, 92, 19],
       [47, 13, 78, 11, 25, 72, 44, 11, 30, 88],
       [41, 11, 36, 78, 56, 48, 40, 57, 95, 35],
       [ 4, 43, 94, 27, 95, 61,  1, 24, 78, 52],
       [29, 32, 49, 73, 40, 79,  0, 48, 59, 38],
       [90, 76, 60, 46, 59, 18,  9, 18, 72, 88],
       [83, 42, 27, 92, 58, 78, 87, 37, 91, 60],
       [16, 90, 28,  4, 60, 38, 31, 63, 66, 64],
       [93, 78, 92, 48, 89,  8, 13, 66, 65,  3]], dtype=int32)

In [74]:
m[2:3,5:8]

array([[72, 44, 11]], dtype=int32)

In [75]:
m[4:9,2:5]

array([[94, 27, 95],
       [49, 73, 40],
       [60, 46, 59],
       [27, 92, 58],
       [28,  4, 60]], dtype=int32)

In [76]:
m[1,2]

np.int32(6)

# Filtering or Masking

In [77]:
m

array([[89, 76, 31, 60, 92,  7, 65,  5,  5, 96],
       [96, 87,  6, 30, 46, 88, 47,  6, 92, 19],
       [47, 13, 78, 11, 25, 72, 44, 11, 30, 88],
       [41, 11, 36, 78, 56, 48, 40, 57, 95, 35],
       [ 4, 43, 94, 27, 95, 61,  1, 24, 78, 52],
       [29, 32, 49, 73, 40, 79,  0, 48, 59, 38],
       [90, 76, 60, 46, 59, 18,  9, 18, 72, 88],
       [83, 42, 27, 92, 58, 78, 87, 37, 91, 60],
       [16, 90, 28,  4, 60, 38, 31, 63, 66, 64],
       [93, 78, 92, 48, 89,  8, 13, 66, 65,  3]], dtype=int32)

In [78]:
m>50

array([[ True,  True, False,  True,  True, False,  True, False, False,
         True],
       [ True,  True, False, False, False,  True, False, False,  True,
        False],
       [False, False,  True, False, False,  True, False, False, False,
         True],
       [False, False, False,  True,  True, False, False,  True,  True,
        False],
       [False, False,  True, False,  True,  True, False, False,  True,
         True],
       [False, False, False,  True, False,  True, False, False,  True,
        False],
       [ True,  True,  True, False,  True, False, False, False,  True,
         True],
       [ True, False, False,  True,  True,  True,  True, False,  True,
         True],
       [False,  True, False, False,  True, False, False,  True,  True,
         True],
       [ True,  True,  True, False,  True, False, False,  True,  True,
        False]])

In [82]:
m[m>50]

array([89, 76, 60, 92, 65, 96, 96, 87, 88, 92, 78, 72, 88, 78, 56, 57, 95,
       94, 95, 61, 78, 52, 73, 79, 59, 90, 76, 60, 59, 72, 88, 83, 92, 58,
       78, 87, 91, 60, 90, 60, 63, 66, 64, 93, 78, 92, 89, 66, 65],
      dtype=int32)

In [83]:
m[m>=50]

array([89, 76, 60, 92, 65, 96, 96, 87, 88, 92, 78, 72, 88, 78, 56, 57, 95,
       94, 95, 61, 78, 52, 73, 79, 59, 90, 76, 60, 59, 72, 88, 83, 92, 58,
       78, 87, 91, 60, 90, 60, 63, 66, 64, 93, 78, 92, 89, 66, 65],
      dtype=int32)

In [84]:
m[m<50]

array([31,  7,  5,  5,  6, 30, 46, 47,  6, 19, 47, 13, 11, 25, 44, 11, 30,
       41, 11, 36, 48, 40, 35,  4, 43, 27,  1, 24, 29, 32, 49, 40,  0, 48,
       38, 46, 18,  9, 18, 42, 27, 37, 16, 28,  4, 38, 31, 48,  8, 13,  3],
      dtype=int32)

In [85]:
m[m<=50]

array([31,  7,  5,  5,  6, 30, 46, 47,  6, 19, 47, 13, 11, 25, 44, 11, 30,
       41, 11, 36, 48, 40, 35,  4, 43, 27,  1, 24, 29, 32, 49, 40,  0, 48,
       38, 46, 18,  9, 18, 42, 27, 37, 16, 28,  4, 38, 31, 48,  8, 13,  3],
      dtype=int32)

In [86]:
m

array([[89, 76, 31, 60, 92,  7, 65,  5,  5, 96],
       [96, 87,  6, 30, 46, 88, 47,  6, 92, 19],
       [47, 13, 78, 11, 25, 72, 44, 11, 30, 88],
       [41, 11, 36, 78, 56, 48, 40, 57, 95, 35],
       [ 4, 43, 94, 27, 95, 61,  1, 24, 78, 52],
       [29, 32, 49, 73, 40, 79,  0, 48, 59, 38],
       [90, 76, 60, 46, 59, 18,  9, 18, 72, 88],
       [83, 42, 27, 92, 58, 78, 87, 37, 91, 60],
       [16, 90, 28,  4, 60, 38, 31, 63, 66, 64],
       [93, 78, 92, 48, 89,  8, 13, 66, 65,  3]], dtype=int32)

In [88]:
m[2] # it display second row

array([47, 13, 78, 11, 25, 72, 44, 11, 30, 88], dtype=int32)

In [90]:
m[:,2] # it display second row 

array([31,  6, 78, 36, 94, 49, 60, 27, 28, 92], dtype=int32)

In [91]:
m

array([[89, 76, 31, 60, 92,  7, 65,  5,  5, 96],
       [96, 87,  6, 30, 46, 88, 47,  6, 92, 19],
       [47, 13, 78, 11, 25, 72, 44, 11, 30, 88],
       [41, 11, 36, 78, 56, 48, 40, 57, 95, 35],
       [ 4, 43, 94, 27, 95, 61,  1, 24, 78, 52],
       [29, 32, 49, 73, 40, 79,  0, 48, 59, 38],
       [90, 76, 60, 46, 59, 18,  9, 18, 72, 88],
       [83, 42, 27, 92, 58, 78, 87, 37, 91, 60],
       [16, 90, 28,  4, 60, 38, 31, 63, 66, 64],
       [93, 78, 92, 48, 89,  8, 13, 66, 65,  3]], dtype=int32)

In [93]:
m[::-1] # reverse the matrix

array([[93, 78, 92, 48, 89,  8, 13, 66, 65,  3],
       [16, 90, 28,  4, 60, 38, 31, 63, 66, 64],
       [83, 42, 27, 92, 58, 78, 87, 37, 91, 60],
       [90, 76, 60, 46, 59, 18,  9, 18, 72, 88],
       [29, 32, 49, 73, 40, 79,  0, 48, 59, 38],
       [ 4, 43, 94, 27, 95, 61,  1, 24, 78, 52],
       [41, 11, 36, 78, 56, 48, 40, 57, 95, 35],
       [47, 13, 78, 11, 25, 72, 44, 11, 30, 88],
       [96, 87,  6, 30, 46, 88, 47,  6, 92, 19],
       [89, 76, 31, 60, 92,  7, 65,  5,  5, 96]], dtype=int32)

In [94]:
m

array([[89, 76, 31, 60, 92,  7, 65,  5,  5, 96],
       [96, 87,  6, 30, 46, 88, 47,  6, 92, 19],
       [47, 13, 78, 11, 25, 72, 44, 11, 30, 88],
       [41, 11, 36, 78, 56, 48, 40, 57, 95, 35],
       [ 4, 43, 94, 27, 95, 61,  1, 24, 78, 52],
       [29, 32, 49, 73, 40, 79,  0, 48, 59, 38],
       [90, 76, 60, 46, 59, 18,  9, 18, 72, 88],
       [83, 42, 27, 92, 58, 78, 87, 37, 91, 60],
       [16, 90, 28,  4, 60, 38, 31, 63, 66, 64],
       [93, 78, 92, 48, 89,  8, 13, 66, 65,  3]], dtype=int32)

In [96]:
m[::-2] # step value

array([[93, 78, 92, 48, 89,  8, 13, 66, 65,  3],
       [83, 42, 27, 92, 58, 78, 87, 37, 91, 60],
       [29, 32, 49, 73, 40, 79,  0, 48, 59, 38],
       [41, 11, 36, 78, 56, 48, 40, 57, 95, 35],
       [96, 87,  6, 30, 46, 88, 47,  6, 92, 19]], dtype=int32)

# numpy operations

In [97]:
arr3 = np.array([1,2,3,4,5])
arr3

array([1, 2, 3, 4, 5])

In [98]:
arr3.max()

np.int64(5)

In [99]:
max(arr3)

np.int64(5)

In [100]:
arr3.min()

np.int64(1)

In [101]:
arr3.mean()

np.float64(3.0)

In [103]:
from numpy import *

In [105]:
median(arr3)

np.float64(3.0)

In [106]:
np.random.randint(0,10,2)

array([3, 6], dtype=int32)

In [107]:
np.random.randint(0,10,5)

array([1, 0, 4, 9, 3], dtype=int32)

In [108]:
np.random.randint(0,10,10)

array([8, 0, 5, 8, 9, 1, 7, 6, 9, 0], dtype=int32)

In [109]:
np.random.randint(0,10,20)

array([5, 6, 8, 2, 4, 2, 6, 7, 7, 3, 5, 7, 5, 9, 4, 7, 5, 2, 4, 3],
      dtype=int32)

In [110]:
np.random.randint(0,10,100)

array([1, 0, 7, 9, 1, 1, 3, 2, 0, 3, 1, 9, 9, 4, 9, 7, 4, 3, 1, 5, 5, 2,
       9, 9, 4, 8, 6, 6, 5, 7, 8, 8, 7, 5, 0, 9, 5, 4, 7, 9, 9, 9, 8, 7,
       1, 0, 9, 7, 1, 5, 0, 4, 6, 6, 6, 2, 8, 9, 8, 8, 1, 0, 6, 6, 8, 3,
       8, 4, 6, 4, 0, 2, 7, 1, 8, 9, 0, 3, 4, 8, 9, 0, 8, 8, 9, 0, 2, 1,
       9, 3, 0, 5, 8, 0, 1, 9, 4, 1, 4, 9], dtype=int32)

In [113]:
np.random.randint(0,10,200).reshape(100,2)

array([[6, 2],
       [8, 5],
       [0, 3],
       [7, 0],
       [9, 1],
       [3, 7],
       [1, 8],
       [1, 0],
       [3, 8],
       [0, 8],
       [6, 5],
       [2, 8],
       [4, 1],
       [3, 8],
       [4, 2],
       [0, 3],
       [4, 8],
       [8, 1],
       [5, 6],
       [0, 4],
       [6, 0],
       [3, 6],
       [7, 1],
       [3, 8],
       [6, 9],
       [4, 8],
       [4, 1],
       [6, 3],
       [7, 5],
       [6, 2],
       [7, 8],
       [2, 2],
       [7, 2],
       [5, 3],
       [5, 8],
       [6, 8],
       [6, 2],
       [5, 3],
       [0, 1],
       [3, 3],
       [6, 9],
       [7, 0],
       [6, 7],
       [1, 5],
       [1, 7],
       [4, 8],
       [3, 4],
       [0, 8],
       [1, 5],
       [2, 7],
       [1, 1],
       [1, 0],
       [0, 3],
       [5, 4],
       [2, 7],
       [7, 8],
       [4, 6],
       [9, 9],
       [9, 8],
       [8, 2],
       [3, 0],
       [9, 6],
       [9, 8],
       [0, 2],
       [5, 5],
       [5, 5],
       [9,

In [125]:
np.arange(10,20).reshape(1,10) # first count elements then reshape

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])